/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsproductIdRouteImport } from './routes/products/(product)/$id'
import { Route as ProductsIdDetailsRouteImport } from './routes/products/$id.details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsproductIdRoute = ProductsproductIdRouteImport.update({
  id: '/products/(product)/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdDetailsRoute = ProductsIdDetailsRouteImport.update({
  id: '/products/$id/details',
  path: '/products/$id/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/$id/details': typeof ProductsIdDetailsRoute
  '/products/$id': typeof ProductsproductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/$id/details': typeof ProductsIdDetailsRoute
  '/products/$id': typeof ProductsproductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$id/details': typeof ProductsIdDetailsRoute
  '/products/(product)/$id': typeof ProductsproductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products' | '/products/$id/details' | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products' | '/products/$id/details' | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/products/'
    | '/products/$id/details'
    | '/products/(product)/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsIdDetailsRoute: typeof ProductsIdDetailsRoute
  ProductsproductIdRoute: typeof ProductsproductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/(product)/$id': {
      id: '/products/(product)/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsproductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id/details': {
      id: '/products/$id/details'
      path: '/products/$id/details'
      fullPath: '/products/$id/details'
      preLoaderRoute: typeof ProductsIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsIdDetailsRoute: ProductsIdDetailsRoute,
  ProductsproductIdRoute: ProductsproductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
